### ISSUE TITLE
Reproducable results 

### ISSUE THREAD

**Issue by BahmanTahayori** [CRG-CNAG/robustica#3]
Thanks for the nice module. The documentation says that if the `random_state` is set to an int, the results will be reproducible. It generates reproducible results when I use `random_state =42`, however,  all the runs results are identical which is not ideal. I also tried `random_state=np.random.RandomState(seed = 42)`, but the results are not reproducible. Is there anything that I am missing?

**Comment by MiqG** [comment]
Hi @BahmanTahayori ,

thanks for pointing that out. You're right. I have fixed the issue and the algorithm should behave as expected passing the arguments you suggested if you install the latest version of the repo.

Best,

Miquel

**Comment by BahmanTahayori** [comment]
Hi @MiqG, 

Thanks for updating the code. I tested it and now it generates reproducible results. 

Best regards,
Bahman

**Comment by BahmanTahayori** [comment]
Hi @MiqG,

Would you please update the package on pypi as well? Thank you in advance. 

Best regards,
Bahman

**Comment by MiqG** [comment]
Hi @BahmanTahayori ,

now you should be able to get the latest version via pypi as well.

Best,

Miquel

**Comment by BahmanTahayori** [comment]
Thank you very much @MiqG.
